import json
import os

GLUE_REGISTRY_NAME = os.getenv("GLUE_REGISTRY_NAME")
GLUE_AWS_REGION = os.getenv("GLUE_AWS_REGION")
KAFKA_BOOTSTRAP_BROKERS = os.getenv("KAFKA_BOOTSTRAP_BROKERS")
KAFKA_SASL_USERNAME = os.getenv("KAFKA_SASL_USERNAME")
KAFKA_SASL_PASSWORD = os.getenv("KAFKA_SASL_PASSWORD")
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS")
AUTH_KEYS = json.loads(os.getenv("AUTH_KEYS", "[]"))
