apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Values.deploymentName }}
  ports:
    - port: 80
      targetPort: 80
