apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
type: Opaque
stringData:
  authKeys: '{{ .Values.authKeys }}'
  kafkaSaslUsername: '{{ .Values.kafkaSaslUsername }}'
  kafkaSaslPassword: '{{ .Values.kafkaSaslPassword }}'
