apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.deploymentName }}
    spec:
      serviceAccountName: raise-events-api
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
          image: {{ .Values.apiImage.name }}:{{ .Values.apiImage.tag }}
          imagePullPolicy: Always
          env:
            - name: CORS_ALLOWED_ORIGINS
              value: {{ .Values.allowedOrigins }}
            - name: GLUE_REGISTRY_NAME
              value: {{ .Values.glueRegistryName }}
            - name: GLUE_AWS_REGION
              value: {{ .Values.glueAwsRegion }}
            - name: KAFKA_BOOTSTRAP_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
                  key: kafkaBootstrapBrokers
            - name: AUTH_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
                  key: authKeys
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
                  key: kafkaSaslUsername
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
                  key: kafkaSaslPassword
          ports:
            - containerPort: 80
