apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-tls-{{ .Values.deploymentName }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{ .Values.deploymentDomain }}-tls
  routes:
    - match: "Host(`{{ .Values.deploymentDomain }}`)"
      kind: Rule
      services:
        - name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
          port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.deploymentDomain }}`)"
      kind: Rule
      middlewares:
        - name: {{ .Chart.Name }}-{{ .Values.deploymentName }}-redirect
      services:
        - name: {{ .Chart.Name }}-{{ .Values.deploymentName }}
          port: 80
